name: Build (Debug)
on: [push, pull_request]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - name: Install NSIS
        uses: negrutiu/nsis-install@v2
      - name: Build and package
        run: dotnet run --project build -- compile
      - uses: actions/upload-artifact@v7
        with:
          name: froststrap-release-win-x64-${{ github.sha }}
          path: .build/msbuild/*

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - name: Publish
        run: dotnet run --project build -- compile
      - uses: actions/upload-artifact@v6
        with:
          name: froststrap-debug-macos-arm64-${{ github.sha }}
          path: .build/msbuild/*

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"
      - name: Publish
        run: dotnet run --project build -- compile
      - uses: actions/upload-artifact@v6
        with:
          name: froststrap-debug-linux-x64-${{ github.sha }}
          path: .build/msbuild/*
